version: '3.1'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80" 
    restart: always
    env_file:
      - ./.env  
    networks:
      npm:
        ipv4_address: 10.1.0.6 

networks:
  npm:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/24 
